# __Atividade Prática:__
#### **Bibliotecas básicas I**

<font size=3>

Enviar cópia deste notebook com as soluções para $\texttt{tiberio.pereira@imd.ufrn.br}$ :
 - **Título do e-mail:** Atividade 1 - AM;
 - Identifique-se com **nome completo**;
 - **Anexe** o notebook **executado** com o nome: \
    $\texttt{atividade1\_am-nome-sobrenome.ipynb}$

**Entregar** até dia **28 de Agosto**.

<br>

---

**ATENÇÃO:** para promover a segurança de *sua* educação, **não utilize ferramentas de IA generativa** para a solução dessa atividade.

---

### **1. Criação de Arrays:**

In [41]:
# Importando biblioteca numpy

import numpy as np

In [42]:
# 1.1 Crie vetor de 1D com os números de 0 a 9:

numeros = list(range(10))
print(numeros)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [43]:
# 1.2 Crie uma matriz 3x3 preenchida com zeros:

matriz = np.zeros((3,3))
print(matriz)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [44]:
# 1.3 Crie uma matriz identidade 4x4:

matriz_identidade = np.eye(4)
print(matriz_identidade)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [45]:
# 1.4 Crie um array 2x2 preenchido com o valor 7:

matriz = np.full((2,2), 7)
print(matriz)

[[7 7]
 [7 7]]


In [46]:
# 1.5 Crie um vetor com 10 valores igualmente espaçados entre 0 e 1:

vetor = np.linspace(0, 1, 10)
print(vetor)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


### **2. Operações com Vetores:**

In [47]:
# 2.1 Dados os vetores a = [1, 2, 3] e b = [4, 5, 6], calcule:
# - A soma de a e b;
# - A multiplicação elemento a elemento (a * b);
# - O produto escalar de a e b.

# Montando as matrizes a e b
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Soma das matrizes
soma = a + b
print(soma)

# Multiplicação das matrizes
produto = a * b
print(produto)

# Escalar das matrizes
escalar = np.dot(a, b)
print(escalar)

[5 7 9]
[ 4 10 18]
32


In [48]:
# 2.2 Calcule a norma (magnitude) do vetor v = [3, 4]:

# Montando vetor
v = np.array([3, 4])

# Calculando magnitude do vetor
magnitude_v = np.linalg.norm(v)
print(magnitude_v)

5.0


In [49]:
# 2.3 Crie um vetor c com valores de 1 a 5 e inverta a ordem dos elementos:

# Motando vetor
c = np.arange(1, 6)
print(c)

# Invertendo a ordem desses elementos do vetor c
c_invertido = np.flip(c)
print(c_invertido)

[1 2 3 4 5]
[5 4 3 2 1]


### **3. Operações com Matrizes:**

In [50]:
# 3.1 Dadas as matrizes A = [[1, 2], [3, 4]] e B = [[5, 6], [7, 8]], calcule:
# - Soma;
# - Produto interno (escalar);
# - Transposta de A.

# Monstando as matrizes
A = np.array([[1, 2], [3, 4]])
print("A \n", A, "\n")
B = np.array([[5, 6], [7, 8]])
print("B \n", B, "\n")

# Somando as matrizes A + B
soma_matrizes = A + B
print("Soma \n", soma_matrizes)

# Produto interno (escalar)
produto = np.dot( A, B)
print("\n", "Produto escalar \n",produto)

# Transposta de A
matriz_transposta = np.transpose(A)
print("\n Transposta de A \n", matriz_transposta)

A 
 [[1 2]
 [3 4]] 

B 
 [[5 6]
 [7 8]] 

Soma 
 [[ 6  8]
 [10 12]]

 Produto escalar 
 [[19 22]
 [43 50]]

 Transposta de A 
 [[1 3]
 [2 4]]


In [51]:
# 3.2 Crie uma matriz 2x3 de distribuição normal com média 0.5 e desvio padrão 0.2:

# Criando uma matriz 2x3
shape = (2,3)

# Definindo as atribuições (media = 0.5 e desvio padrao = 0.2)
media = 0.5
dp = 0.2

# Cria a matriz com distribuição normal
matriz = np.random.normal(media, dp, shape)

# Imprime a matriz
print(matriz)

[[0.16743762 0.4469226  0.41276135]
 [0.82734763 0.71264545 0.67001014]]


### **4. Indexação e Slicing:**

In [52]:
# 4.1 Dado o vetor x = [10, 20, 30, 40, 50]:
# - Acesse o terceiro elemento;
# - Extraia os elementos do segundo ao quarto.

# Constuindo o vetor
vetor = np.array([10, 20, 30, 40, 50])

# Acessando o terceiro elemento
terceiro_elemento = vetor[2]

# Elementos do segundo ao quarto
segundo_ao_quarto_elemento = vetor[1:4]

print("Terceiro elemento do vetor:", terceiro_elemento, "\n")
print("Elemento do segundo ao quarto:", segundo_ao_quarto_elemento)

Terceiro elemento do vetor: 30 

Elemento do segundo ao quarto: [20 30 40]


In [53]:
# 4.2 Dada a matriz D = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]:
# - Acesse o elemento na segunda linha e terceira coluna.
# - Extraia a submatriz das duas primeiras linhas e colunas.

# Construindo a matriz
D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

elemento = D[1, 2]
print(elemento)

6


### **5. Funções Estatísticas:**

In [54]:
# 5.1 Dado o vetor y = [1, 5, 3, 8, 2], calcule:
# - A média, mediana e desvio padrão;
# - O valor máximo e mínimo.

# Cosntruindo vetor
y = [1, 5, 3, 8, 2]

# Média
media = np.mean(y)

# Mediana
mediana = np.median(y)

# Desvio padrão
desvio = np.std(y)

valor_max = np.max(y)
valor_min = np.min(y)

print("Média:", media)
print("Mediana:", mediana)
print("Desvio padrão:", desvio)
print("Máximo:", valor_max)
print("Mínimo:", valor_min)

Média: 3.8
Mediana: 3.0
Desvio padrão: 2.481934729198171
Máximo: 8
Mínimo: 1


In [55]:
# 5.2 Calcule o valor máximo das colunas da matriz E = [[1, 2], [3, 4]]:

vator = [[1, 2], [3, 4]]
max_colunas = np.max(vator, axis=0)
print(max_colunas)

[3 4]


### **6. Reshape e Concatenção:**

In [56]:
# 6.1 Transforme o vetor [1, 2, 3, 4, 5, 6] em uma matriz 2x3:

# Construindo o vetor
vetor = np.array([1, 2, 3, 4, 5, 6])

matriz = vetor.reshape((2, 3))
print(matriz)

[[1 2 3]
 [4 5 6]]


In [57]:
# 6.2 Concatene verticalmente as matrizes F = [[1, 2]] e G = [[3, 4]]:

F = np.array([[1, 2]])
G = np.array([[3, 4]])

H = np.vstack((A, G))

print(H)

[[1 2]
 [3 4]
 [3 4]]
